### ISSUE TITLE
Avoid downloading neighboring geometries

### ISSUE THREAD

**Issue by shishkin** [kraina-ai/quackosm#110]
When specifying `Monaco` to get a geometry and then use that geometry to download and convert OSM into parquet, quackosm downloads 346 MB of `files/Geofabrik_provence-alpes-cote-d-azur.osm.pbf` instead of 527 KB of the actual [Monaco PBF](https://download.geofabrik.de/europe/monaco.html).

I also tried the same with [Regierungsbezirk Düsseldorf](https://www.openstreetmap.org/relation/63306). Quackosm downloads neighboring Münster and Köln. That is almost 325 MB more than just 190 MB asked.

When downloading [Germany](https://www.openstreetmap.org/relation/51477), Quackosm also downloads Denmark, Austria, and Czechia.

Is there a way to avoid downloading unneeded OSM files?

**Comment by RaczeQ** [comment]
Hello @shishkin
For now, this if the expected behaviour, because QuackOSM tries to cover given geometry fully and extracts geometries not always line-up perfectly with geocoded ones.

### Monaco
I've plotted the geocoded geometry for clause `Monaco` (https://www.openstreetmap.org/relation/1124039) in yellow, and Geofabrik extract geometry for Monaco (http://download.geofabrik.de/europe/monaco.html) in red.
![image](https://github.com/kraina-ai/quackosm/assets/17250607/59554b5e-344b-4b1e-91ef-b670bbeb4563)

As you can see, there is a huge chunk of sea area that is returned by Nominatim, that isn't covered by extract from Geofabrik.

But, changing the PBF source from `geofabrik` to `osmfr` will solve the issue for your use case:
![image](https://github.com/kraina-ai/quackosm/assets/17250607/8ad752d4-5a84-4150-a253-8096898c9656)

```python
import quackosm as qosm
import osmnx as ox

qosm.convert_geometry_to_geodataframe(
    geometry_filter=ox.geocode_to_gdf("Monaco").unary_union, osm_extract_source="osmfr"
)
```
```bash
quackosm --geom-filter-geocode Monaco --osm-extract-source osmfr
```

### Düsseldorf

![image](https://github.com/kraina-ai/quackosm/assets/17250607/b0a3250f-5b47-4ce4-9b7a-3e38d195df5b)
Here switching to `osmfr` source can also help.

### Germany

![image](https://github.com/kraina-ai/quackosm/assets/17250607/97244d79-4c96-4d3a-b21a-0fc1024bd307)
Again `osmfr` source can also help.

### Summary

By default QuackOSM uses only Geofabrik extracts, because scraping BBBike and OSMfr takes a long time to do, but these services could contain better matching geometries for particular use cases. Also, Geofabrik has better coverage of the whole world than OpenStreetMap.fr, but they don't have enough buffer around extracts to fully cover Nominatim-based geometries.

Looking at those examples, I think I can fix the issue regarding Germany and Düsseldorf case for Geofabrik default source, by discarding new extracts if their contribution to overall geometry is insignificant (for example less than 1% of the queried geometry).

**OSM_fr** index - better precision in particular areas, but some gaps outside Europe
![image](https://github.com/kraina-ai/quackosm/assets/17250607/69b8e51c-b442-41f0-8036-e4ba72fc3e7b)

**Geofabrik** index - more uniform coverage
![image](https://github.com/kraina-ai/quackosm/assets/17250607/b5fc83fa-9f5e-47d1-a078-864289099544)

**Comment by shishkin** [comment]
I see. I'm actually confused by what you call "Nominatim-based geometries". Aren't all geometries coming from OSM unchanged, where Nomimatim is a search index and Geofabrik, osmfr and others are just repackaging the same OSM world.pbf in smaller pieces? I get that the nature of boundaries is very complicated, but so far Geofabrik slicing seem quite practical. I would actually even prefer to just specify names of Geofabrik extracts directly (like `duesseldorf-regbez`) in order to reuse quackosm's caching.

**Comment by RaczeQ** [comment]
Nominatim can be a source of truth, but all of those services can define their geometries and names.
BBBike for example serves rectangular extracts around cities detached from administrative geometries.

I've added two issues to tackle the problems mentioned here:
- #115
- #119

**Comment by shishkin** [comment]
@RaczeQ That's awesome! Thanks a lot. Look forward to test the new version.
