### ISSUE TITLE
osm-tags-filter with CLI

### ISSUE THREAD

**Issue by CaptainInler** [kraina-ai/quackosm#131]
I don't get `--osm-tags-filter` working.

I get this result when I use the [command from the Documentation](https://kraina-ai.github.io/quackosm/0.8.1/examples/command_line_interface/#osm-tags-filters):
``` python
quackosm monaco-latest.osm.pbf --osm-tags-filter '{ "building": true }'
Usage: QuackOSM [OPTIONS] PBF file path.
Try 'QuackOSM -h' for help.
╭─ Error ──────────────────────────────────────────────────────────────────────────────────────────╮
│ Invalid value for '--osm-tags-filter': Cannot parse provided OSM tags filter                     │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
```
The same error occurs with a '=' according to [osm-tags-filter without specific tag](https://github.com/kraina-ai/quackosm/discussions/48):
``` python
quackosm monaco-latest.osm.pbf --osm-tags-filter='{ "building": true }'
```
    
------    
Filtering with File works as expected:
``` python
quackosm monaco-latest.osm.pbf --osm-tags-filter-file filterfile.json
```
where the content of filterfile.json is:
``` json
{"building": true}
```

----
tested on quackosm version 0.7.3. to 0.8.2

**Comment by RaczeQ** [comment]
Hello @CaptainInler 

I'm sorry to hear that you're having troubles using this filter functionality in the CLI mode.

Could you also share what is the operating system that you're using and what shell are you using?

This use-case is tested by mocking the terminal and has been working on 3 major platforms (Windows, OS X, Linux)
https://github.com/kraina-ai/quackosm/blob/09cd61262284e00af6cfc8c24662b7de7eee8d5c/tests/base/test_cli.py#L106-L122

However, I was able to reproduce this error using the PowerShell and CMD on Windows 10 machine.
It turns out that there is a PowerShell bug with improper quotation marks parsing: https://github.com/PowerShell/PowerShell/issues/1995

Even though the string is escaped using single-quotes, double quotes are being stripped before passing the value to the python script. I was able to run this modified command (had to escape double quotes):

PowerShell
```powershell
 quackosm monaco-latest.osm.pbf --osm-tags-filter '{ \"building\": true }'
```

CMD (doesn't work with single quotes at all)
```cmd
 quackosm monaco-latest.osm.pbf --osm-tags-filter "{ \"building\": true }"
```

**Comment by CaptainInler** [comment]
Hi @RaczeQ thank you for your fast reply.
I'm on Windows and using CMD.
Of course I should have thought of the problem with the quotes myself :see_no_evil: thanks for pointing me in this direction :+1:

**Comment by RaczeQ** [comment]
I'm going to close this issue because of the inactivity. I hope your problem got resolved with previous comments 🙂
