### ISSUE TITLE
Problems with filtering OSM features of type "relation" - Specifically Tag:route=bus

### ISSUE THREAD

**Issue by dinorastoder** [kraina-ai/quackosm#172]
Hi,

While working on data regarding bus routes in Montenegro I noticed that filtering bus routes is failing from [Geofabrik Montenegro file.](https://download.geofabrik.de/europe/montenegro.html)

Example of code
```python
import  quackosm as qosm
filter_bus = {"route": "bus"} 
gdf = qosm.convert_pbf_to_geodataframe("files/geofabrik_europe_montenegro.osm.pbf", tags_filter=filter_bus, keep_all_tags=True)
gdf.size    # Output: 0
```

Example of feature in OSM: https://www.openstreetmap.org/relation/16053240
![image](https://github.com/user-attachments/assets/0d7363b3-381b-442c-94a8-88560d0370a5)

**Comment by RaczeQ** [comment]
Hello @dinorastoder 

The short answer to you question is that it is working as intended, because `routes` in OSM don't represent physical objects.

The long answer is: QuackOSM has similar logic to the OSMnx library and only relations with tag `type` equal to `boundary` or `multipolygon` are extracted in the process.

https://github.com/kraina-ai/quackosm/blob/9d4124929269dd9b68c75c573159b2db54422621/quackosm/pbf_file_reader.py#L1464-L1479

You can read more about it here: https://wiki.openstreetmap.org/wiki/Relation#Multipolygon

But, if you are interested in bus routes for this particular use case, you can use this script to get geometries of stops and routes:

```python
import quackosm as qosm
import duckdb

# Load highway and public_transport features
highway_filter = {"highway": True, "public_transport": True}

features_gdf = qosm.convert_osm_extract_to_geodataframe(
    "geofabrik_europe_montenegro", tags_filter=highway_filter, keep_all_tags=True
)

# Load bus routes data using DuckDB
duckdb.load_extension("spatial")
bus_routes_unnested = duckdb.sql(
    """
    SELECT
        id,
        tags as route_tags,
        UNNEST(refs) as ref,
        UNNEST(ref_types) as ref_type,
        UNNEST(ref_roles) as ref_role
    FROM ST_ReadOSM("files/geofabrik_europe_montenegro.osm.pbf")
    WHERE kind = 'relation'
    AND tags['route'][1] = 'bus'
    """
).to_df()

# Join the data
bus_routes_unnested["feature_id"] = (
    bus_routes_unnested["ref_type"].astype(str) + "/" + bus_routes_unnested["ref"].astype(str)
)
bus_routes_with_geometries = bus_routes_unnested.merge(features_gdf, left_on="feature_id", right_index=True)
bus_routes_with_geometries = bus_routes_with_geometries.rename(
    columns={
        "id": "relation_route_id",
        "tags": "feature_tags",
    }
)

# Check if any features is missing
missing_features = bus_routes_unnested[
    ~bus_routes_unnested["feature_id"].isin(bus_routes_with_geometries["feature_id"])
]


```

**Comment by dinorastoder** [comment]
Ok. That is fair! 
Then this issue should be closed 🔒 

Thank you so much on quick response and this detailed solution. I will try to work out something from that. 

//Dino
