### ISSUE TITLE
Filter by osm-tags-filter but preserve all tags in result

### ISSUE THREAD

**Issue by StephanGeorg** [kraina-ai/quackosm#25]
Hi @RaczeQ

Thank you so much for all your work building this tool. 

I want to filter by `osm-tags-filter` but want to preserve all available tags in the result.

At the moment

```bash 
quackosm berlin-latest.osm.pbf --osm-tags-filter='{"landuse":"allotments"}' 
```

filters all `allotments` but the result does only contain the `landuse` tag.

Thanks for a quick hint.

**Comment by RaczeQ** [comment]
Hi @StephanGeorg, I can confirm that this is how the tool is currently behaving.
What's more, that was actually by design and I left a cheeky note for the future to add this functionality:
https://github.com/kraina-ai/quackosm/blob/482e3090dfbefd7fae4374267ad045be0f12465e/quackosm/pbf_file_reader.py#L1516-L1524

When I started working with OSM data I only cared about whether the element matched a given tag filter so I only kept the columns I needed, but I can see why this might be a crucial functionality.

I'll try to add parameters for this in the near future and also add an option to pass `osm-tags-filter` as a `.json` file path.

**Comment by StephanGeorg** [comment]
Thank you so much. Looking forward to `# TODO: elif keep other tags ` 😉

**Comment by RaczeQ** [comment]
I've added a `keep_all_tags` parameter to the API, so in CLI you can add `--keep-all-tags` (or `--all-tags`) as an option:

```
quackosm berlin-latest.osm.pbf --osm-tags-filter='{"landuse":"allotments"}' --keep-all-tags
```

There is also a new `--osm-tags-filter-file` for more advanced filter configurations.

Just update the library to the `0.3.3` version (currently is still building).

Screenshot from the new docs:
![image](https://github.com/kraina-ai/quackosm/assets/17250607/d9f97384-96ca-4e0a-bfcf-61a87036ddb5)

**Comment by StephanGeorg** [comment]
Hey @RaczeQ.  Just tested it and works as expected. Thank you very much for the fast response and work you're doing bringing OSM, DuckDB, Geoparquet, Parquet stack to the next level.
